### ISSUE TITLE
change link in href

### ISSUE THREAD

**Issue by daniel-bergmann** [Basilcss/reactjs-basilcss-template#1]
the link has to be changed to href="https://basilcss.com"

**Comment by jss530** [comment]
hello! I can take on this issue and the other issue if they're still open. I am going to post the same comment on the second open one.

**Comment by daniel-bergmann** [comment]
@jss530 fantastic, go ahead! :)

**Comment by jss530** [comment]
Great, PR [here](https://github.com/Basilcss/reactjs-basilcss-template/pull/3)

**Comment by daniel-bergmann** [comment]
Good job, keep up the good work! :)
