### ISSUE TITLE
change of text

### ISSUE THREAD

**Issue by daniel-bergmann** [Basilcss/reactjs-basilcss-template#2]
Switch React JS with React.js and Basil CSS with Basil.css

**Comment by jss530** [comment]
hello! I can take on this issue and the other issue if they're still open. I am going to post the same comment on the second open one.

**Comment by daniel-bergmann** [comment]
@jss530 fantastic, go ahead! :)

**Comment by jss530** [comment]
Great, PR [here](https://github.com/Basilcss/reactjs-basilcss-template/pull/4)

**Comment by daniel-bergmann** [comment]
Good job, keep up the good work! :)
